[2024-06-04T17:58:31.665+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: send_message_and_calculate_ABC.send_message_and_calculate_ABC scheduled__2024-06-02T07:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
