[2024-06-12T18:21:15.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T18:21:15.864+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T18:21:09.080576+00:00 [queued]>
[2024-06-12T18:21:15.872+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T18:21:09.080576+00:00 [queued]>
[2024-06-12T18:21:15.872+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-06-12T18:21:15.882+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parsing_wb> on 2024-06-12 18:21:09.080576+00:00
[2024-06-12T18:21:15.891+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T18:21:15.892+0000] {standard_task_runner.py:63} INFO - Started process 741 to run task
[2024-06-12T18:21:15.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parsing_wb_mpstats', 'parsing_wb', 'manual__2024-06-12T18:21:09.080576+00:00', '--job-id', '1440', '--raw', '--subdir', 'DAGS_FOLDER/parsing_wb_mpstats/parsing.py', '--cfg-path', '/tmp/tmp8oi2kppx']
[2024-06-12T18:21:15.894+0000] {standard_task_runner.py:91} INFO - Job 1440: Subtask parsing_wb
[2024-06-12T18:21:15.950+0000] {task_command.py:426} INFO - Running <TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T18:21:09.080576+00:00 [running]> on host d40bdb4a74ef
[2024-06-12T18:21:16.041+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parsing_wb_mpstats' AIRFLOW_CTX_TASK_ID='parsing_wb' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T18:21:09.080576+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T18:21:09.080576+00:00'
[2024-06-12T18:21:16.043+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T18:21:30.629+0000] {logging_mixin.py:188} INFO - 4
[2024-06-12T18:26:13.985+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-06-12T18:26:13.986+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-12T18:26:13.988+0000] {process_utils.py:132} INFO - Sending 15 to group 741. PIDs of all processes in the group: [741]
[2024-06-12T18:26:13.988+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 741
[2024-06-12T18:26:13.988+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-12T18:26:13.990+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T18:26:14.005+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing.py", line 36, in get_nmids_and_run_parsing_wb
    return main_wb(nmids=result['nmids'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 348, in main
    data_all_nmids_current, data_all_nmids_previous = get_data_from_wb(nmids)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 324, in get_data_from_wb
    data_all_nmids_previous = get_detail_history_report(nmids_list, df_p, dt_p)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 265, in get_detail_history_report
    response = make_request_to_wb(url_generate_report, 'POST', request_body).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 78, in make_request_to_wb
    time.sleep(TIME_SLEEP)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-12T18:26:14.009+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=parsing_wb_mpstats, task_id=parsing_wb, execution_date=20240612T182109, start_date=20240612T182115, end_date=20240612T182614
[2024-06-12T18:26:14.022+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1440 for task parsing_wb ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(parsing_wb_mpstats, parsing_wb, manual__2024-06-12T18:21:09.080576+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'parsing_wb', 'dag_id': 'parsing_wb_mpstats', 'run_id': 'manual__2024-06-12T18:21:09.080576+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 6, 12, 18, 21, 15, 864375, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 6, 12, 18, 26, 14, 9155, tzinfo=Timezone('UTC')), 'duration': 298}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 741)
[2024-06-12T18:26:14.040+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=741, status='terminated', exitcode=1, started='18:21:15') (741) terminated with exit code 1
