[2024-07-23T07:24:27.484+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T07:24:27.513+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_message_and_calculate_ABC.send_message_and_calculate_ABC manual__2024-07-23T07:24:25.770441+00:00 [queued]>
[2024-07-23T07:24:27.521+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_message_and_calculate_ABC.send_message_and_calculate_ABC manual__2024-07-23T07:24:25.770441+00:00 [queued]>
[2024-07-23T07:24:27.522+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-07-23T07:24:27.536+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_message_and_calculate_ABC> on 2024-07-23 07:24:25.770441+00:00
[2024-07-23T07:24:27.545+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=151646) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-23T07:24:27.546+0000] {standard_task_runner.py:63} INFO - Started process 151648 to run task
[2024-07-23T07:24:27.547+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'send_message_and_calculate_ABC', 'send_message_and_calculate_ABC', 'manual__2024-07-23T07:24:25.770441+00:00', '--job-id', '2678', '--raw', '--subdir', 'DAGS_FOLDER/send_message_and_calculate_ABC.py', '--cfg-path', '/tmp/tmpyuq89shk']
[2024-07-23T07:24:27.548+0000] {standard_task_runner.py:91} INFO - Job 2678: Subtask send_message_and_calculate_ABC
[2024-07-23T07:24:27.607+0000] {task_command.py:426} INFO - Running <TaskInstance: send_message_and_calculate_ABC.send_message_and_calculate_ABC manual__2024-07-23T07:24:25.770441+00:00 [running]> on host d40bdb4a74ef
[2024-07-23T07:24:27.720+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_message_and_calculate_ABC' AIRFLOW_CTX_TASK_ID='send_message_and_calculate_ABC' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T07:24:25.770441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T07:24:25.770441+00:00'
[2024-07-23T07:24:27.720+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T07:24:34.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T07:24:34.840+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/send_message_and_calculate_ABC.py", line 653, in start_dag
    main()
  File "/opt/airflow/dags/send_message_and_calculate_ABC.py", line 645, in main
    write_categories_to_google_sheet(categories, vendorCode_dict)
  File "/opt/airflow/dags/send_message_and_calculate_ABC.py", line 416, in write_categories_to_google_sheet
    for ind, val in enumerate(sheet_ABC.col_values(6)[1:], start=2):
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/worksheet.py", line 712, in col_values
    data = self.client.values_get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 231, in values_get
    r = self.request("get", url, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 123, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 429, 'message': "Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:735755711859'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_location': 'global', 'quota_metric': 'sheets.googleapis.com/read_requests', 'consumer': 'projects/735755711859', 'quota_limit_value': '60', 'quota_limit': 'ReadRequestsPerMinutePerUser', 'service': 'sheets.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}
[2024-07-23T07:24:34.859+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=send_message_and_calculate_ABC, task_id=send_message_and_calculate_ABC, execution_date=20240723T072425, start_date=20240723T072427, end_date=20240723T072434
[2024-07-23T07:24:34.872+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2678 for task send_message_and_calculate_ABC ({'code': 429, 'message': "Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:735755711859'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_location': 'global', 'quota_metric': 'sheets.googleapis.com/read_requests', 'consumer': 'projects/735755711859', 'quota_limit_value': '60', 'quota_limit': 'ReadRequestsPerMinutePerUser', 'service': 'sheets.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}; 151648)
[2024-07-23T07:24:34.921+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-23T07:24:34.943+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T07:24:34.944+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
